[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=936
DialogFontName=Microsoft YaHei UI
DialogFontSize=9

[Messages]
SetupAppTitle=安装 %1
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载 %1
UninstallAppFullTitle=%1 卸载程序
InformationTitle=信息
ConfirmTitle=确认
ErrorTitle=错误
SetupLdrStartupMessage=现在将安装 %1，是否继续？
LdrCannotCreateTemp=无法创建临时文件，安装已取消。
LdrCannotExecTemp=无法执行临时目录中的安装程序。
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=本向导将在您的电脑上安装 [name/ver]。%n%n继续前请关闭其他应用程序。
ClickNext=单击“下一步”继续，或单击“取消”退出安装。
WizardSelectDir=选择安装位置
SelectDirDesc=[name] 安装到何处？
SelectDirLabel3=安装程序将把 [name] 安装到以下文件夹。
SelectDirBrowseLabel=单击“下一步”继续；如需更改位置，请单击“浏览”。
DiskSpaceGBLabel=至少需要 [gb] GB 可用磁盘空间。
WizardReady=准备安装
ReadyLabel1=安装程序已准备就绪。
ReadyLabel2a=单击“安装”开始，或单击“上一步”检查设置。
WizardInstalling=正在安装
InstallingLabel=请稍候，正在安装 [name]。
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=安装已完成。
FinishedLabel=安装已完成，可通过已创建的快捷方式启动软件。
ButtonBack=< 上一步
ButtonNext=下一步 >
ButtonInstall=安装
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是
ButtonNo=否
ButtonBrowse=浏览...
ButtonFinish=完成
BrowseDialogTitle=选择文件夹
BrowseDialogLabel=选择一个文件夹，然后单击“确定”。
NewFolderName=新建文件夹
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。确定要退出吗？
AboutSetupMenuItem=关于安装程序...
AboutSetupTitle=关于安装程序
UninstallNotFound=文件“%1”不存在，无法卸载。
UninstallStatusLabel=请稍候，正在卸载 %1。
UninstalledAll=卸载完成。%n%n工作区和 .cvat-local 数据未删除。
